integrated_task:
  paths:
    input_dir: "./input"
    output_dir: "./output"

  # Prediction with network information using DPMON.
  prediction:
    network_file: "global_network.csv"
    omics_files:
      - "metabolites_blood_count_adjusted_2019-08-26.csv"
      - "proteins_blood_count_adjusted_protein_names.csv"

    phenotype_file: "Y_finalgold_coarse.csv"

    # Featues file with clinical data for nodes
    features_file: ""

    # parameters for the model
    model: ""
    gpu: ""
    cuda: ""
    tune: ""

    # Other parameters for dpmon
    gnn_layer_num: ""
    gnn_hidden_dim: ""
    lr: ""
    weight_decay: ""
    nn_hidden_dim1: ""
    nn_hidden_dim2: ""
    num_epochs: ""
    repeat_num: ""
