# /m3_network_embedding/config/config.yml

network_embedding:
  paths:
    input_dir: "../input"
    output_dir: "../output"

  node2vec:
    embedding_dim: 128
    walk_length: 80
    num_walks: 10
    window_size: 10
