clustering:
  paths:
    input_dir: "../input"
    output_dir: "../output"

  Hierarchical:
    n_clusters: 3
    linkage: "ward"
    affinity: "euclidean"

  PageRank:
    damping_factor: 0.85
    max_iter: 100
    tol: 1e-6
