name: Build Documentation for Read the Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          check-latest: true

      - name: List repository contents
        run: ls -la

      - name: List docs directory contents
        run: ls -la docs/

      - name: Run setup-env.sh (Non-Interactive)
        env:
          INSTALL_TYPE: 1   # cpu only
          INSTALL_DEV: y    # dev dependencies
        run: |
          chmod +x scripts/setup-env.sh
          ./scripts/setup-env.sh

      # Build and install the package
      - name: Build and install package
        run: |
          source .venv/bin/activate
          pip install -e .

      - name: Build Documentation
        run: |
          source .venv/bin/activate
          sphinx-build -b html docs/source/ docs/build/html/

      - name: Validate Documentation Build
        run: |
          echo "Documentation build completed successfully. Files are located in docs/build/html/"
          ls -R docs/build/html/
