name: BioNeuralNet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # All OS
        python-version: [3.8, 3.9, 3.10]                  # All Python versions

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies with fast-install.py
      shell: bash
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          python script/fast-install.py
        else
          chmod +x script/setup-env.sh
          chmod +x script/setup-R.sh
          python script/fast-install.py
        fi

    - name: Verify R installation
      shell: bash
      run: |
        R --version
        Rscript -e "library(WGCNA); cat('WGCNA loaded successfully')"

    - name: Run tests with pytest
      run: |
        pytest --cov=bioneuralnet --cov-report=xml tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
