name: BioNeuralNet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] 
        python-version: ['3.8']                  

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        check-latest: true

    - name: Print working directory
      run: pwd

    - name: List scripts directory contents
      run: ls -la scripts/

    - name: Run setup-env.sh (Non-Interactive)
      env:
        INSTALL_TYPE: 1 #use cpu
        INSTALL_DEV: y  #install dev dependencies
      run: |
        chmod +x scripts/setup-env.sh
        ./scripts/setup-env.sh

    - name: Verify R installation
      shell: bash
      run: |
        R --version
        Rscript -e "library(WGCNA); cat('WGCNA loaded successfully')"

    - name: Run tests with pytest
      run: |
        pytest --cov=bioneuralnet --cov-report=xml tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
