paths:
  input_dir: './input'
  log_dir: './logs'
  output_dir: './output'

smccnet:
  omics_file: 'omics_data.csv'
  phenotype_file: 'phenotype_data.csv'
  data_types: 'protein, metabolite'
  kfold: 5
  summarization: 'PCA'
  seed: 732

wgcna:
  omics_file: 'omics_data.csv'
  phenotype_file: 'phenotype_data.csv'
  soft_power: 6
  min_module_size: 30
  merge_cut_height: 0.25

gnn_embedding:
  model_type: 'GCN'
  gnn_hidden_dim: 64
  gnn_layer_num: 2
  dropout: true

node2vec_embedding:
  embedding_dim: 128
  walk_length: 80
  num_walks: 10
  window_size: 10



